# Generated by Django 2.2.4 on 2019-09-06 18:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20190904_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('title', models.TextField(verbose_name='Content Title')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Url Field')),
                ('html_content', models.TextField(blank=True, null=True, verbose_name='Html Content')),
                ('meta_data', django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='Content Metada')),
                ('duration', models.TimeField(blank=True, null=True, verbose_name='Estimated Duration')),
                ('expertise_percentage', models.FloatField(null=True, verbose_name='Expertise Percentage')),
                ('content_area', models.ForeignKey(help_text='Content Area.', on_delete=django.db.models.deletion.CASCADE, to='users.ContentArea')),
                ('content_type', models.ForeignKey(help_text='Type of content.', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.ContentType')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
