# Generated by Django 2.2.4 on 2019-09-06 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190904_2027'),
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContentType',
            new_name='Content',
        ),
    ]
