# Generated by Django 2.2.4 on 2019-09-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contenttype_preferencecontentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='Content area name')),
                ('slug_name', models.SlugField(max_length=40, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='preferencecontentprofile',
            name='content_type',
        ),
        migrations.AddField(
            model_name='preferencecontentprofile',
            name='content_type',
            field=models.ManyToManyField(null=True, to='users.ContentType'),
        ),
        migrations.AddField(
            model_name='preferencecontentprofile',
            name='area',
            field=models.ManyToManyField(to='users.ContentArea'),
        ),
    ]
