# Generated by Django 2.2.4 on 2019-09-10 12:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_preferencecontentprofile_expertise_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencecontentprofile',
            name='meta_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Profile Preference Metada'),
        ),
    ]
