# Generated by Django 2.2.4 on 2019-09-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190904_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencecontentprofile',
            name='content_type',
            field=models.ManyToManyField(to='users.ContentType'),
        ),
    ]
